[package]
name = "dirac_chess"
version = "0.1.0"
authors = ["Dathan Ault-McCoy <dsam10@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3"